### ISSUE TITLE
Generic Parser failes to read some PSU data archives.

### ISSUE THREAD

**Issue by Zetta1-Reid0** [Agrathejagged/tenora-works#1]
I tried uncompressing all data files that PSU has with the "Generic Parser". Some of them could not be uncompressed. for example one of them is archive 00b0c27651f3cccb2a88e8a9e4a6aca6 . But others work completely fine like e5e28a0c0565ca517613d2336144ad75 . More precisely those that start with "4E 4D 4C 4C 02" are parsed correctly . But others that start with "80 00 03 38 03" don't.

**Comment by Agrathejagged** [comment]
00b0c27651f3cccb2a88e8a9e4a6aca6 is an adx file (specifically the Parum lobby music). The parser's unlikely to ever support any of these, but if you'd like to listen to it, you can run it through degod.exe (available at https://hcs64.com/vgm_ripping.html), and then play it with any software that can play ADX files, such as https://gamebanana.com/tools/6491 .

**Comment by Zetta1-Reid0** [comment]
So not all files are archives ?

**Comment by Agrathejagged** [comment]
That's correct. ADX files are for streamed music; they're closer to being like an mp3 or a .flac file than to anything the parser can read.

**Comment by Zetta1-Reid0** [comment]
I see . I should check what type they are before trying to extract them.I just assumed that every file is an archive.Thank you for the info.
